esphome:
  name: $name
  friendly_name: $friendly_name
  name_add_mac_suffix: true
  project:
    name: $project_name
    version: $project_version 
  on_boot:
    then:
      - text_sensor.template.publish:
          id: device_id
          state: !lambda 'return get_mac_address();'

esp32:
  board: esp32-c6-devkitc-1
  variant: ESP32C6
  framework:
    type: esp-idf
    platform_version: 6.5.0
    version: 5.1.0

substitutions:
  status_led_inverted: "false"

text_sensor:
  - platform: template
    name: Device ID
    id: device_id
    entity_category: diagnostic
    update_interval: never
    
sensor:
  - platform: uptime
    name: Uptime
    entity_category: diagnostic

button:
  - platform: restart
    name: Restart
    entity_category: config
  # - platform: factory_reset
  #   name: Factory Reset
  #   entity_category: config
